### ISSUE TITLE
Serializing DOM that uses undefined namespace prefixes in attributes produces invalid XML

### ISSUE THREAD

**Issue by pdecat** [xmldom/xmldom#243]
This is a continuation of https://github.com/xmldom/xmldom/pull/168 which fixed the issue in some cases but not all as revealed in
https://github.com/xmldom/xmldom/pull/168#issuecomment-853925485

```
# git diff
diff --git a/test/parse/node.test.js b/test/parse/node.test.js
index 6c10dc8..acde64e 100644
--- a/test/parse/node.test.js
+++ b/test/parse/node.test.js
@@ -88,13 +88,13 @@ describe('XML Node Parse', () => {
        })

        it('prefixed without empty namespace', () => {
-               const source = '<w:p><w:r>test1</w:r><w:r>test2</w:r></w:p>'
+               const source = '<w:p><w:r><w:rPr><w:rFonts w:ascii=\"FreeSans\" w:hAnsi=\"FreeSans\"/><w:color w:val=\"FF0000\"/></w:rPr><w:t>test1</w:t></w:r><w:r><w:t>test2</w:t></w:r></w:p>'
                const { documentElement } = new DOMParser().parseFromString(source)

-               expect(documentElement.firstChild.firstChild).toMatchObject({
+               expect(documentElement.firstChild.lastChild.firstChild).toMatchObject({
                        nodeValue: 'test1',
                })
-               expect(documentElement.lastChild.firstChild).toMatchObject({
+               expect(documentElement.lastChild.firstChild.firstChild).toMatchObject({
                        nodeValue: 'test2',
                })

```

```
# ./node_modules/jest/bin/jest.js -t "prefixed without empty namespace"
 FAIL  test/parse/node.test.js
  ● XML Node Parse › prefixed without empty namespace

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "<w:p><w:r><w:rPr><w:rFonts w:ascii=\"FreeSans\" w:hAnsi=\"FreeSans\"/><w:color w:val=\"FF0000\"/></w:rPr><w:t>test1</w:t></w:r><w:r><w:t>test2</w:t></w:r></w:p>"
    Received: "<w:p><w:r><w:rPr><w:rFonts xmlns:w=\"\" w:ascii=\"FreeSans\" w:hAnsi=\"FreeSans\"/><w:color w:val=\"FF0000\"/></w:rPr><w:t>test1</w:t></w:r><w:r><w:t>test2</w:t></w:r></w:p>"

       99 |             })
      100 |
    > 101 |             expect(documentElement.toString()).toStrictEqual(source)
          |                                                ^
      102 |     })
      103 |
      104 |     it('cdata comment', () => {

      at Object.<anonymous> (test/parse/node.test.js:101:38)


Summary of all failing tests
 FAIL  test/parse/node.test.js
  ● XML Node Parse › prefixed without empty namespace

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "<w:p><w:r><w:rPr><w:rFonts w:ascii=\"FreeSans\" w:hAnsi=\"FreeSans\"/><w:color w:val=\"FF0000\"/></w:rPr><w:t>test1</w:t></w:r><w:r><w:t>test2</w:t></w:r></w:p>"
    Received: "<w:p><w:r><w:rPr><w:rFonts xmlns:w=\"\" w:ascii=\"FreeSans\" w:hAnsi=\"FreeSans\"/><w:color w:val=\"FF0000\"/></w:rPr><w:t>test1</w:t></w:r><w:r><w:t>test2</w:t></w:r></w:p>"

       99 |             })
      100 |
    > 101 |             expect(documentElement.toString()).toStrictEqual(source)
          |                                                ^
      102 |     })
      103 |
      104 |     it('cdata comment', () => {

      at Object.<anonymous> (test/parse/node.test.js:101:38)


Test Suites: 1 failed, 28 skipped, 1 of 29 total
Tests:       1 failed, 573 skipped, 574 total
Snapshots:   0 total
Time:        2.227 s, estimated 3 s
Ran all test suites with tests matching "prefixed without empty namespace".
```

**Comment by karfau** [comment]
Thank you for reporting.
From the test output you provided, it looks like the empty namespace is still added when there are any attributes with that namespace involved, so most likely we can reduce the complexity of the example.
I'll have a look into it.

**Comment by karfau** [comment]
See this comment for a reason why this might be a breaking change: https://github.com/xmldom/xmldom/pull/168#issuecomment-886984994
